### PR TITLE
Allows grouped likert bars to plot.percents

### PR DESCRIPTION
**Pull request by larcat**
Changed lines 186 through 202.

Edited work done at http://stackoverflow.com/questions/20057697/plot-percents-with-likert-package-doesnt-work-when-grouping

Fixed some bugs with above.

### CODE REVIEW

**Comment by jbryer** [comment]
Thanks for this @larcat I copied your code over since the pull request had conflicts.

**Comment by larcat** [comment]
Oh, cool! Did it end up making it in then?

-D

**Comment by jbryer** [comment]
Yes. It is on Github now. I'll do some more testing before releasing to
CRAN, hopefully within the next week or so.

**Comment by larcat** [comment]
Awesome! Thanks for all your work :D

-D

**Pull request closed without merging**
